server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /products {
        proxy_pass http://product-service:3001;
    }

    location /orders {
        proxy_pass http://order-service:3002;
    }


    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}